export function generateInvoicePDF(order, userName) {
  const items = order.items || [];
  const orderId = order.id?.slice(-8)?.toUpperCase() || 'N/A';
  const date = new Date(order.created_date || Date.now()).toLocaleDateString('es-ES');
  const rowsHtml = items.map(i => '<tr><td>' + i.name + '</td><td style="text-align:center">' + i.quantity + '</td><td>$' + Number(i.price).toFixed(2) + '</td><td><strong>$' + (i.price*i.quantity).toFixed(2) + '</strong></td></tr>').join('');
  const html = '<!DOCTYPE html><html lang="es"><head><meta charset="UTF-8"><title>Factura #' + orderId + '</title><style>*{margin:0;padding:0;box-sizing:border-box}body{font-family:Segoe UI,sans-serif;background:#fff;color:#111;padding:40px}.logo{font-size:28px;font-weight:900;color:#22C55E}table{width:100%;border-collapse:collapse;margin-bottom:24px}th{text-align:left;font-size:11px;color:#9CA3AF;text-transform:uppercase;padding:8px 12px;border-bottom:2px solid #E5E7EB}td{padding:10px 12px;border-bottom:1px solid #F3F4F6;font-size:14px}.total{font-size:18px;font-weight:900;color:#22C55E}.footer{text-align:center;margin-top:40px;color:#9CA3AF;font-size:12px}</style></head><body><div style="display:flex;justify-content:space-between;margin-bottom:40px"><div><div class="logo">ShopNest</div><div style="color:#6B7280;font-size:14px">Factura #' + orderId + ' | ' + date + '</div></div><div style="background:#DCFCE7;color:#15803D;padding:6px 14px;border-radius:20px;font-size:12px;font-weight:700">&#10003; Pagado</div></div><table><thead><tr><th>Producto</th><th>Cant.</th><th>Precio</th><th>Total</th></tr></thead><tbody>' + rowsHtml + '</tbody></table><div style="background:#F9FAFB;border-radius:12px;padding:20px"><div style="display:flex;justify-content:space-between;padding:6px 0;font-size:14px"><span>Subtotal</span><span>$' + Number(order.subtotal||0).toFixed(2) + '</span></div><div style="display:flex;justify-content:space-between;padding:6px 0;font-size:14px"><span>Env&iacute;o</span><span>$' + Number(order.shipping||0).toFixed(2) + '</span></div><div style="display:flex;justify-content:space-between;padding-top:12px;margin-top:8px;border-top:2px solid #E5E7EB" class="total"><span>TOTAL</span><span>$' + Number(order.total||0).toFixed(2) + '</span></div></div><div class="footer"><p>Gracias por tu compra en ShopNest &#128154;</p></div></body></html>';
  const blob = new Blob([html], { type: 'text/html' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url; a.download = 'factura-' + orderId + '.html';
  document.body.appendChild(a); a.click(); document.body.removeChild(a); URL.revokeObjectURL(url);
}